### PR TITLE
Begin treewalk interpreter (WIP)

### PR DESCRIPTION
**Pull request by rwblickhan**
## :construction_worker: Changes

Begins a treewalk interpreter and refactors so that REPL uses it.

## :flashlight: Testing Instructions

Run durian without a filepath.

### CODE REVIEW

**Review by bobheadxi — APPROVED** [review]
whoahhhhh

**Comment by rwblickhan** [comment]
thanks fren

**Comment by rwblickhan** [comment]
sadly all checks have failed

**Comment by rwblickhan** [comment]
think we'll ever come back to durian?

**Comment by bobheadxi** [comment]
unfortunately might not have the time to come back to this :( I don't mind merging it just so everything's in one place, for the sake of posterity - it's a decently sized chunk o code

**Comment by rwblickhan** [comment]
Yeah I definitely don't have time to come back to it... would rather work on my Rust implementation, probably 😛 

Honestly this PR is pretty broken... can probably just close it.

**Pull request closed without merging**
